from typing import Dict, Any, List

# ------------------------------------------------------------------
# Severity Calculation Utility
#
# Purpose:
# Determines how serious a handwriting issue is by comparing
# the measured deviation against an expected acceptable range.
#
# Severity Levels:
# - Low    : Deviation is within acceptable limits.
# - Medium : Deviation exceeds the expected range.
# - High   : Deviation is significantly larger than expected.
# ------------------------------------------------------------------

def calculate_severity(deviation: float, expected_range: float) -> str:
    """
    Calculates severity level based on deviation ratio.
    """

    # Prevent division by zero or invalid range values
    if expected_range <= 0:
        return "Low"

    # Compare actual deviation against expected tolerance
    ratio = deviation / expected_range

    if ratio > 2.0:
        return "High"
    elif ratio >= 1.0:
        return "Medium"
    else:
        return "Low"


# ------------------------------------------------------------------
# Feedback Templates
#
# Child Mode:
# Friendly and encouraging language suitable for young learners.
#
# Advanced Mode:
# More detailed and technical guidance suitable for adults,
# teachers, or advanced learners.
# ------------------------------------------------------------------

TEMPLATES = {
    "child": {
        "spacing": "Try to keep the spaces between your letters and words more even!",
        "baseline": "Your letters are floating! Try to write straight on the imaginary line.",
        "slant": "Make sure all your letters lean the same way, like trees in the wind.",
        "stroke": "Try to press on the paper with the same amount of strength."
    },

    "advanced": {
        "spacing": "Inconsistent spacing detected. Try to maintain uniform gaps.",
        "baseline": "High baseline deviation. Practice writing on ruled lines to improve alignment.",
        "slant": "Inconsistent slant angles. Focus on maintaining a uniform vertical axis.",
        "stroke": "Inconsistent stroke thickness. Try to maintain uniform pressure."
    }
}


# ------------------------------------------------------------------
# Feedback Generation Engine
#
# Purpose:
# Converts extracted handwriting features into actionable,
# prioritized feedback messages.
#
# Workflow:
# 1. Verify confidence score.
# 2. Analyze spacing quality.
# 3. Analyze baseline alignment.
# 4. Analyze slant consistency.
# 5. Analyze stroke consistency.
# 6. Rank issues by severity and impact.
# 7. Return the most important issues.
#
# Supported Modes:
# - child
# - advanced
# ------------------------------------------------------------------

def generate_feedback(
    features: Dict[str, Any],
    config: Dict[str, Any] = None
) -> Dict[str, Any]:
    """
    Generates actionable feedback based on feature deviations.

    Mode can be:
    - child
    - advanced
    """

    # --------------------------------------------------------------
    # Initialize configuration
    # --------------------------------------------------------------
    config = config or {}

    # Default feedback style
    mode = config.get("mode", "advanced")

    # Expected acceptable ranges
    EXPECTED_SPACING_RANGE = config.get(
        "expected_spacing_range",
        0.5
    )

    EXPECTED_BASELINE_RANGE = config.get(
        "expected_baseline_range",
        5.0
    )

    # Minimum confidence required for reliable analysis
    CONFIDENCE_THRESHOLD = config.get(
        "confidence_threshold",
        0.5
    )

    # Container for generated feedback items
    feedback_items = []

    # ==============================================================
    # CONFIDENCE CHECK
    # ==============================================================

    # Retrieve confidence metrics generated by the intelligence layer
    confidence_metrics = features.get(
        "confidence_metrics",
        {}
    )

    confidence_score = confidence_metrics.get(
        "score",
        1.0
    )

    # --------------------------------------------------------------
    # If confidence is too low, analysis may be unreliable.
    # Return image quality feedback immediately.
    # --------------------------------------------------------------
    if confidence_score < CONFIDENCE_THRESHOLD:

        if mode == "child":
            feedback_items.append({
                "issue": "quality",
                "severity": "High",
                "message":
                    "The picture is a bit too blurry or small for me to read properly! Can you take a better one?",
                "score_impact": 0
            })
        else:
            feedback_items.append({
                "issue": "quality",
                "severity": "High",
                "message":
                    "Image quality or text density is too low for accurate analysis. Please provide a clearer sample.",
                "score_impact": 0
            })

        # Short-circuit the pipeline because results are unreliable
        features["feedback"] = {
            "mode": mode,
            "issues": feedback_items
        }

        return features

    # ==============================================================
    # FEEDBACK HELPER
    # ==============================================================

    # Tracks issues already added to avoid duplicates
    added_issues = set()

    def add_feedback(
        issue_type: str,
        severity: str,
        impact: int
    ):
        """
        Adds a feedback item if it has not already
        been included.
        """

        if issue_type not in added_issues:

            # Fallback to advanced templates if mode is invalid
            template_mode = (
                mode if mode in TEMPLATES
                else "advanced"
            )

            # Retrieve feedback message template
            text = TEMPLATES[template_mode].get(
                issue_type,
                f"Check your {issue_type}."
            )

            feedback_items.append({
                "issue": issue_type,
                "severity": severity,
                "message": text,
                "score_impact": impact
            })

            added_issues.add(issue_type)

    # ==============================================================
    # 1. SPACING FEEDBACK
    # ==============================================================

    word_features = features.get(
        "word_features",
        {}
    )

    # Standard deviation of spacing values
    spacing_std = word_features.get(
        "spacing_consistency",
        0.0
    )

    spacing_severity = calculate_severity(
        spacing_std,
        EXPECTED_SPACING_RANGE
    )

    if spacing_severity in ["High", "Medium"]:
        add_feedback(
            "spacing",
            spacing_severity,
            20
        )

    # ==============================================================
    # 2. BASELINE FEEDBACK
    # ==============================================================

    line_features = features.get(
        "line_features",
        {}
    )

    # Baseline deviation measurement
    baseline_std = line_features.get(
        "baseline_deviation",
        0.0
    )

    baseline_severity = calculate_severity(
        baseline_std,
        EXPECTED_BASELINE_RANGE
    )

    if baseline_severity in ["High", "Medium"]:
        add_feedback(
            "baseline",
            baseline_severity,
            25
        )

    # ==============================================================
    # 3. SLANT & STROKE FEEDBACK
    # ==============================================================

    char_features = features.get(
        "character_features",
        {}
    )

    # Character slant variation
    slant_std = char_features.get(
        "slant_variance",
        0.0
    )

    # Stroke thickness variation
    stroke_std = char_features.get(
        "stroke_variance",
        0.0
    )

    EXPECTED_SLANT_RANGE = config.get(
        "expected_slant_range",
        10.0
    )

    EXPECTED_STROKE_RANGE = config.get(
        "expected_stroke_range",
        0.2
    )

    # --------------------------------------------------------------
    # Slant consistency feedback
    # --------------------------------------------------------------
    if calculate_severity(
        slant_std,
        EXPECTED_SLANT_RANGE
    ) in ["High", "Medium"]:

        add_feedback(
            "slant",
            calculate_severity(
                slant_std,
                EXPECTED_SLANT_RANGE
            ),
            15
        )

    # --------------------------------------------------------------
    # Stroke consistency feedback
    # --------------------------------------------------------------
    if calculate_severity(
        stroke_std,
        EXPECTED_STROKE_RANGE
    ) in ["High", "Medium"]:

        add_feedback(
            "stroke",
            calculate_severity(
                stroke_std,
                EXPECTED_STROKE_RANGE
            ),
            10
        )

    # ==============================================================
    # PRIORITY RANKING
    # ==============================================================

    # Higher values indicate more important issues
    severity_order = {
        "High": 3,
        "Medium": 2,
        "Low": 1
    }

    # Sort by severity first, then score impact
    feedback_items.sort(
        key=lambda x: (
            severity_order.get(
                x["severity"],
                0
            ),
            x.get("score_impact", 0)
        ),
        reverse=True
    )

    # Keep only the most important feedback items
    top_issues = feedback_items[:3]

    # ==============================================================
    # FINAL FEEDBACK OBJECT
    # ==============================================================

    features["feedback"] = {
        "mode": mode,
        "issues": top_issues
    }

    return features
